name: Update README

on:
  push:
    paths:
      - 'Program.cs'
      - 'Reposcore/**'
      - 'docs/**'
  workflow_dispatch:

jobs:
  generate-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install dependencies
        run: dotnet restore

      - name: Generate README
        run: |
          dotnet run --project Reposcore/Reposcore.csproj -- generate-readme > README.md

      - name: Commit and push if README.md changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git diff --staged --quiet || git commit -m "ci: auto-update README.md"
          git push
